apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
  labels:
    app: nodejs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: aks-k8s-rollouts
          image: aks-k8s-rollouts
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: '/tmp/local-git-repo'
              name: local-git-repo
              readOnly: true
      volumes:
        - name: local-git-repo
          hostPath:
            path: '/tmp/local-git-repo'
            type: Directory